application: tripinproj
version: dev
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

# - url: .*
#   static_files: wait.html
#   upload: wait.html

- url: .*
  script: app.py