application: tripinproj
version: dev
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

# - url: .*
#   static_files: wait.html
#   upload: wait.html

- url: /favicon.ico
  static_files: /static/favicon.ico
  upload: /static/favicon.ico

- url: .*
  script: app.py